### ISSUE TITLE
Compare chart - "capacity" between patient

### ISSUE THREAD

**Issue by akiya64** [hktang/covid-hyogo#8]
I think hospital beds number is very important information, but one of most sensitive issue.

## Realiy useful?
This project should be to help prevent infection for citizens, not to fuel the crisis.
Is this chart that comparison hospital beds with patient useful for preventing community-acquired infections?

## Difficulty of ”Capacity" definition
What is "Capacity"?
1. Hospital beds prepared for COVID-19
2. Hotels for non-severe patient, Hyogo.pref has yet decided use hotels.

There will also be waiting at home for non-severe.  
And may Accept patients across prefectures.

## Difficulty of Infomation resouce
The number of beds is gradually increased, but no daily announced.
And annouce by PDF, it is difficult to crawl.
Example, nothing about beds in this page, need to open PDF and written by japanese.
https://web.pref.hyogo.lg.jp/kk03/200129.html

Daily discharges is not announced, only discharged total.

**Comment by hktang** [comment]
Hi @akiya64 ,

Thank you for raising this extremely important point. 

I completely agree with your point that the visualizations must not spread panic or fuel the crisis. If so, it defeats the original purpose of producing *responsible* charts. That's also another reason we must only use official data published by the Hyogo prefecture. 

That said, I still believe the usefulness of showing the number of beds available versus the number of people still admitted to hospitals. To me, we are at a time where more caution is needed than ever. If this information helps readers understand the need to practise social distancing in order to preserve the precious medical resources, then I would say responsibly showing this number is of merit. 

Perhaps similar to avoid featuring the cumulated numbers, we must also avoid *featuring* the number of beds available. In that sense, I wonder if "toning it down" using lines with neutral/grey colours will be helpful. 

Regarding the data source, could you point me to which page the above PDF is available? I had a hard time looking for it...

Best regards,
X

**Comment by akiya64** [comment]
> Regarding the data source, could you point me to which page the above PDF is available? I had a hard time looking for it...

[新型コロナウイルスの対応について](https://web.pref.hyogo.lg.jp/kk03/200129.html)
![2020-04-06_14h35_30](https://user-images.githubusercontent.com/14228487/78526142-14b05180-7814-11ea-816e-9416fd83bf58.png)
Here link to https://web.pref.hyogo.lg.jp/kk03/corona_teigen0324.html#corona_teigen0324-3
And "corona_teigen0324.html" page announced 

> 現在の入院患者数92人に対して、感染症指定医療機関を中心に246床の受入可能病床を確保しており、県内の当面の入院医療体制は確保されているといえる。

In English by Google Translate.

> For the current 92 inpatients, 246 beds have been secured, centered on medical institutions designated for infectious diseases, and it can be said that the immediate hospital care system in the prefecture has been secured.

Data source that hyogo.pref aims to 500beds is here.
https://web.pref.hyogo.lg.jp/kk03/0403coronataiouhoushin.html#taishohoushin1

**Comment by hktang** [comment]
Googling [site:web.pref.hyogo.lg.jp "病床確保"](https://www.google.com/search?client=firefox-b-d&channel=trow2&sxsrf=ALeKk00csD2hnVomlfAAC42TwJD-hRBZfg%3A1586178632958&ei=SCqLXs6VOpj1wAOPqrLgBA&q=site%3Aweb.pref.hyogo.lg.jp+%22%E7%97%85%E5%BA%8A%E7%A2%BA%E4%BF%9D%22&oq=site%3Aweb.pref.hyogo.lg.jp+%22%E7%97%85%E5%BA%8A%E7%A2%BA%E4%BF%9D%22&gs_lcp=CgZwc3ktYWIQA0oKCBcSBjEyLTEwNEoICBgSBDEyLTJQw35Yw35g-IABaABwAHgAgAF1iAHLAZIBAzEuMZgBAKABAqABAaoBB2d3cy13aXo&sclient=psy-ab&ved=0ahUKEwjO2d7v79PoAhWYOnAKHQ-VDEwQ4dUDCAs&uact=5) shows the earliest mention is 154床 on March 1st. This number is valid until [March 19](https://www.kobe-np.co.jp/news/sougou/202003/0013204362.shtml). The number 246床 was announced on March 24th. 

Maybe we can add these two data points and draw a dotted line between them (March 1, March 24)?

**Comment by hktang** [comment]
Hi @akiya64,

As we are not sure how the capacity is increasing after March 24th, I guess it's better to show  two points as mentioned earlier. This is what I've come up with so far (deployed here: https://covid-hyogo-49x6c1zgo.now.sh/).

With more numbers coming in, this chart will be more informative, I am sure...

![Screenshot_2020-04-06 COVID-19 in Hyogo, Japan](https://user-images.githubusercontent.com/2219830/78567522-c888ff80-785b-11ea-987d-0920f8f1a704.png)

**Comment by akiya64** [comment]
@hktang 
I think it is better way to show capacity growth.
Display by dotted line and dot announced day, this way guess  represents the real data more accurately.

And, I found Hyogo.pref had announced that available beds is 246 in April 3 again.
Refer https://web.pref.hyogo.lg.jp/kk03/0403coronataiouhoushin.html#taishohoushin1
![2020-04-07_07h40_59](https://user-images.githubusercontent.com/14228487/78611981-24c34200-78a3-11ea-8a0a-51c8dfddf03b.png)

**Comment by hktang** [comment]
Let me merge the changes. Will watch this page for updates! 
Thank you again for the great information.
